### ISSUE TITLE
Really hope this sdk would support cocoapods.

### ISSUE THREAD

**Issue by lbj96347** [Nexmo/verify-ios-sdk#1]
If this sdk would support cocoapods,it would be more easy to import this sdk into developers' apps.Hope Nexmo team would consider this requirement.:-)

**Comment by dozzman** [comment]
Hi lbj96347,

Unfortunately there are some compatibility issues with including Google Cloud Messaging and Swift/Framework based pods within the same target. This is currently preventing deploying the SDK on cocoapods, but I agree -- it would be a little simpler to integrate the SDK into an application.

We are keeping an eye on the situation and hope to include cocoapods support whenever possible.
