### ISSUE TITLE
CALL DISCONNECT

### ISSUE THREAD

**Issue by allen8300** [Nexmo/verify-ios-sdk#12]
Guys, did you meet the circumstance that, when verifying, the phone call is always dropped, so that user cannot receive the verification code.
Everything works well before updating to Swift3.0.
It's such a critical issue. 
Anyone to help out?

**Comment by shams-ahmed** [comment]
@allen8300 am unable to reproduce this bug. can you go through the steps?

**Comment by allen8300** [comment]
Hi, thanks so much for replying.  
I understand that your system treats 19 seconds duration as success. 
While, after I updating to swift 3.0, I test with two phone number, always meet with following case:
For the calls to 861352167XXXX: 
   A: The 1st call is only up for a duration of 5 seconds, then dropped, so I cannot heard the full code.
   B: Then a few minutes later, I get second call which up for about 19 seconds,  I finally get the code.

For the calls to 861830154XXXX: 
   The 1st call: same as above A case, which dropped within about 5 seconds.
   Then a few minutes later, I get second call which up for about 19 seconds，but I can't heard anything, which means even the call lasts for 19 seconds, but I didn't get the code.

My worry is, if 1st call always dropped, even I can receive verification code successfully from the second call , it's already timeout. Isn't it?

On the other hand, for verifying module, I can only receive code as voice call now, why I cannot receive code as sms as before?

**Comment by shams-ahmed** [comment]
@allen8300 is it possible to submit a ticket to [Support](https://help.nexmo.com/hc/en-us/categories/200202603-Verify) with a link to this thread. they will be able to look into the logs and find out why the calls have dropped. 

from what your saying this doesn't look like an SDK specific issue as the call is handled by the OS and our Verify platform.

**Comment by allen8300** [comment]
@shams-ahmed , yes, I already checked with the support, but nobody reply my email these two days.
Were you guys on holiday or weekend?

**Comment by shams-ahmed** [comment]
Sorry about the delayed response. in the support thread I can see peter been assisting you in the last few days, please bear with us while we diagnosis the issue..

**Comment by shams-ahmed** [comment]
I’m closing this issue because it has been inactive for more than a week. This probably means that it is not reproducible or it has been fixed in a newer version.

Thank you!
