### ISSUE TITLE
Unable to find a specification

### ISSUE THREAD

**Issue by sschizas** [Nexmo/verify-ios-sdk#13]
!] Unable to find a specification for `NexmoVerify`

This error receive when running  **pod install**

Cocoapods version: 1.1.1

**Comment by shams-ahmed** [comment]
it on [cocoapods spec repo](https://cocoapods.org/?q=nexmoverify). can you update your local spec repo or clean it with:

```
 $ sudo rm -fr ~/.cocoapods/repos/master
 $ pod setup
```

**Comment by shams-ahmed** [comment]
I’m closing this issue because it has been inactive for more than a week. This probably means that it is not reproducible or it has been fixed in a newer version. 

Thank you!

**Comment by sschizas** [comment]
@shams-ahmed The cocoapod for NexmoVerify disappeared completely from cocoapods.org. What happened?

**Comment by shams-ahmed** [comment]
hi @n3trino, we found some issues with last cocoapod version that would have made some users unable to verify, until this is resolved we pulled our cocoapods release. I've reopened this ticket will update you very soon

**Comment by shams-ahmed** [comment]
@n3trino Our latest version on cocoapods out 

https://cocoapods.org/pods/NexmoVerify
