### ISSUE TITLE
Support for iOS 8?

### ISSUE THREAD

**Issue by DarkInsight85** [Nexmo/verify-ios-sdk#15]
Hi, from the podspec it is stated that this library is only supported on iOS 9 and later. However, when I checkout the project, I see that in the project settings, the minimum deployment target is still iOS 8.

May I know if iOS 8 is supported?

**Comment by shams-ahmed** [comment]
@DarkInsight85 i don't see why not, I'll push another pod update soon

**Comment by DarkInsight85** [comment]
Thanks a lot mate.
