### ISSUE TITLE
support for swift3?

### ISSUE THREAD

**Issue by mrchenhao** [Nexmo/verify-ios-sdk#16]

**Comment by jodihum** [comment]
Sorry about that @mrchenhao, our swift3 branch momentarily disappeared.  It is back now. It is still a beta.  Please let us know if you encounter any problems.  

Cheers

**Comment by mrchenhao** [comment]
It' difficult to migrate to Swift 3  so I have to use the rest API to replace.

**Comment by shams-ahmed** [comment]
Our latest version on cocoapods supports swift 3

https://cocoapods.org/pods/NexmoVerify
