### ISSUE TITLE
only supported swift 3.0 

### ISSUE THREAD

**Issue by ghafartanveer** [Nexmo/verify-ios-sdk#18]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by shams-ahmed** [comment]
@ghafartanveer what swift version do you require?

**Comment by ghafartanveer** [comment]
swift 2.3

**Comment by shams-ahmed** [comment]
```Apple: “Xcode 8.2 is the last release that will support Swift 2.3. Please migrate your projects from Swift 2.3 code to Swift 3”```

We will not official support or maintain swift 2.3 version on verify as of this...
