### ISSUE TITLE
Swift3 branch of Nexmo compile error due to underscore notation

### ISSUE THREAD

**Issue by robomotic** [Nexmo/verify-ios-sdk#20]
## Expected Behavior

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
CompileSwift normal arm64 /tmp/sandbox/workspace/verify-ios-sdk/VerifyIosSdk/LogoutResponse.swift
CompileSwift normal arm64 /tmp/sandbox/workspace/verify-ios-sdk/VerifyIosSdk/ControlService.swift
## Actual Behavior

Compile failure for the three files, seems to be due to new notation:

/tmp/sandbox/workspace/verify-ios-sdk/VerifyIosSdk/ControlService.swift:[27,29] function types cannot have argument label 'response'; use '_' instead
    ✗                onResponse: (response: ControlResponse?, error: NSError?) -> ())
   
## Steps to Reproduce the Problem

  1.Xcode 8.2.1
  2.Create a new Swift3 project
  3.Add Nexmo Swift 3 branch
  4. Compile
## Specifications

  - Version Nexmo Swift 3 branch commit: 6646a9eb51ee3601546e2dcc9de85d1b8fae2bf1
  - Platform: OSX
  - Subsystem:XCode 8.2.1.

**Comment by shams-ahmed** [comment]
@robomotic Can you try using `master` branch or using newest pod with:
```
pod 'NexmoVerify'
```

Swift 3 branch will be removed in favor of master branch which is now swift 3 compatible and fully maintained now
