### ISSUE TITLE
Server Side Validation - access to request_id

### ISSUE THREAD

**Issue by civocr** [Nexmo/verify-ios-sdk#21]
## Expected Behavior
Verification works well internally on the device, however there is no way to validate the user communicating with our server is authorised.

## Actual Behavior

No access to request_id: 'ID_RETURNED_IN_THE_VERIFY_RESPONSE',

## Steps to Reproduce the Problem

  1. 
`[VerifyClient getVerifiedUserWithCountryCode:_countryCode phoneNumber:_internationalNumber verifyInProgressBlock:^{
        NSLog(@"verification in progress");
    } userVerifiedBlock:^{
        NSLog(@"verified happened");
        [self verified];
    } errorBlock:^(enum VerifyError error) {
        NSLog(@"%ld",(long)error);
    }];`

  2. `-(void)verified {
// No way here to send to http://myserver/verifyphone and have server validate request_id
/*
  Node server:
      api.nexmo.com/verify/check/json
*/
}`
  
## Requested enhancement
Is it possible for getVerifiedUserWithCountryCode to have the request_id passed onto the callback so that the server is then able to do its own secure authentication

## Specifications

  - Version: latest
  - Platform: iOS

**Comment by ec19846** [comment]
You could use the Verify Search User Status API (docs attached) in your backend to implement server-side validation.

There is a 3rd party implementation of this here: https://github.com/hashlabs/nexmo-verify-go-sdk

We are in the process of creating a sample app implementing backend validation and making the search api docs public.

[VerifySDKServiceSearchAPI (2) (2).pdf](https://github.com/Nexmo/verify-ios-sdk/files/700140/VerifySDKServiceSearchAPI.2.2.pdf)
