### ISSUE TITLE
Compiler warning Swift 3.1

### ISSUE THREAD

**Issue by neokree** [Nexmo/verify-ios-sdk#23]
## Expected Behavior
Installing sdk with cocoapods will load it without compiler warnings

## Actual Behavior
On build there are some compiler warnings, mostly on `String(describing:)`

## Steps to Reproduce the Problem

  1. Build a project with XCode 8.3.1 and Swift 3.1

## Specifications

  - XCode version: 8.3.1
  - Swift version: 3.1

**Comment by shams-ahmed** [comment]
@neokree We planning to deploy another version which supports Swift 3.1 and Xcode 8.3.2 in the next 24 hours.
