### ISSUE TITLE
 Supporting IPv6

### ISSUE THREAD

**Issue by phukhanhlee** [Nexmo/verify-ios-sdk#25]
Does nexmo iOS SDK support IPv6 ?
Please check and update if it is not supported. Because Apple Store now require support IPv6. I check source file(SDKDeviceProperties.h) and seem it just support v4 (AF_INET).

-(NSString*)getIpAddress {
    NSString *address = NULL;
    struct ifaddrs *interfaces = NULL;
    struct ifaddrs *temp_addr = NULL;
    int success = 0;
    // retrieve the current interfaces - returns 0 on success
    success = getifaddrs(&interfaces);
    if (success == 0) {
        // Loop through linked list of interfaces
        temp_addr = interfaces;
        while(temp_addr != NULL) {
            if (temp_addr->ifa_addr->sa_family == AF_INET &&
                temp_addr->ifa_flags & IFF_RUNNING &&
                temp_addr->ifa_flags & IFF_UP &&
                !(temp_addr->ifa_flags & IFF_LOOPBACK)) {
                // Get NSString from C String
                address = [NSString stringWithUTF8String:inet_ntoa(((struct sockaddr_in *)temp_addr->ifa_addr)->sin_addr)];
                break;
            }
            temp_addr = temp_addr->ifa_next;
        }
    }
    // Free memory
    freeifaddrs(interfaces);
    return address;
}

Here is the solutions (http://stackoverflow.com/questions/37693256/required-ipv6-compatibility-ios-app-rejected-by-apple)
Please confirm and check ? 

Thanks,
Khanh Le

**Comment by shams-ahmed** [comment]
Does nexmo iOS SDK support IPv6?

Unfortunately, it doesn't support it yet, we will look into does this very soon

**Comment by phukhanhlee** [comment]
Thanks! Please update as soon as possible because Apple now requires supporting IPv6

**Comment by shams-ahmed** [comment]
@phukhanhlee can we pushed a patch now, can you try use our development version:
```
pod 'NexmoVerify', :git => "git@github.com:Nexmo/verify-ios-sdk.git", branch => "master" # Development version
```

Cocoapods release will be tomorrow, once we finished some manal test

**Comment by shams-ahmed** [comment]
@phukhanhlee NexmoVerify 1.0.7 out now.

Please let me know if you have any other issues

**Comment by phukhanhlee** [comment]
@shams-ahmed Thank you so much for quick support !
