### ISSUE TITLE
support swift 2.3 ?

### ISSUE THREAD

**Issue by andiesupriyatna** [Nexmo/verify-ios-sdk#26]
Hi nexmo team

i want to integrate nexmo with my ios app that still swift 2.3
where i can find url to use it?
im using cocoapods

thank you

**Comment by shams-ahmed** [comment]
Apple: “Xcode 8.2 is the last release that will support Swift 2.3. Please migrate your projects from Swift 2.3 code to Swift 3”

We will not official support or maintain swift 2.3 version on verify as of this...
