### ISSUE TITLE
Please add CocoaPods support

### ISSUE THREAD

**Issue by delebedev** [Nexmo/verify-ios-sdk#4]

**Comment by sschizas** [comment]
Yes please add cocoapods support and also look out for Swift 3 update as there are plenty warnings in the current version of Verify SDK.

**Comment by n3trino** [comment]
Any comment??

**Comment by dozzman** [comment]
@n3trino, thanks for the heads up about Swift 3 warnings. You can expect an update shortly.
@garnett cocoapods support incoming too you'll be glad to hear.

Cheers,

Dorian

**Comment by dozzman** [comment]
@n3trino swift warnings have been amended.

**Comment by sschizas** [comment]
@dozzman any update on cocoapods support?

**Comment by shams-ahmed** [comment]
We now support pods: 

```
pod 'NexmoVerify'
```

**Comment by sschizas** [comment]
@shams-ahmed any update on missing cocoapod from cocoapods.org???

**Comment by shams-ahmed** [comment]
@n3trino we won't be releasing an updated pod until our platform fully supports APNS since google is no longer recommending Google GCM as a push solution. I'll update you as soon as i get confirmation... if you need a temp solution i would drag the project in your workspace until it released

**Comment by sschizas** [comment]
@shams-ahmed from which branch? the swift3 branch?

**Comment by shams-ahmed** [comment]
@n3trino `swift3` correct

**Comment by shams-ahmed** [comment]
pod 'NexmoVerify'

Now on cocoapods 🎉
