### ISSUE TITLE
missing the Frameworks 

### ISSUE THREAD

**Issue by Abel7x** [Nexmo/verify-ios-sdk#5]
The binarie frameworks are missing

**Comment by dozzman** [comment]
The SDK does not ship with binary frameworks. All the code is compiled within your Xcode project after you import it.

**Comment by Abel7x** [comment]
Ok then a noob question… how do I compile the frameworks to Xcode let me import them into the embedded binary section of my project. 

-- 
Abel Vivanco
Sent with Airmail

On January 21, 2016 at 18:10:35, Dorian Peake (notifications@github.com) wrote:

The SDK does not ship with binary frameworks. All the code is compiled within your Xcode project after you import it.

**Comment by dozzman** [comment]
All the information you need to  integrate the SDK into your own project is available here.

https://docs.nexmo.com/sdks/verify-sdk/verify-sdk-for-iOS/prerequisites#configure

Note that you'll need to have a Nexmo Verify SDK app to successfully use the Verify SDK.

https://docs.nexmo.com/sdks/verify-sdk/verify-sdk-for-iOS/prerequisites#prereq

**Comment by Abel7x** [comment]
I was following that guide, I already have a app on my nexmo account but in this specific step:

Select VerifyIosSdk.framework.iOS, DeviceProperties.framework.iOS andRequestSigning.framework.iOS in VerifyIosSDK.xcodeproj and click Add.
Xcode won’t import the those binaries because they aren’t there in the “VerifyIosSdk.xcodeproj”.

-- 
Abel Vivanco
Sent with Airmail

On January 21, 2016 at 18:17:53, Dorian Peake (notifications@github.com) wrote:

All the information you need to integrate the SDK into your own project is available here.

https://docs.nexmo.com/sdks/verify-sdk/verify-sdk-for-iOS/prerequisites#configure

Note that you'll need to have a Nexmo Verify SDK app to successfully use the Verify SDK.

https://docs.nexmo.com/sdks/verify-sdk/verify-sdk-for-iOS/prerequisites#prereq

**Comment by Abel7x** [comment]
Event the examples won't run

<img width="251" alt="screen shot 2016-01-21 at 18 42 00" src="https://cloud.githubusercontent.com/assets/2066716/12499268/ab7bba76-c06e-11e5-9a82-41ee0898b49d.png">

<img width="264" alt="screen shot 2016-01-21 at 18 42 16" src="https://cloud.githubusercontent.com/assets/2066716/12499273/b693856a-c06e-11e5-97c0-ea29c8fa8d49.png">

**Comment by dozzman** [comment]
Can you try cleaning the Xcode project (CMD + OPTION + SHIFT + K) and see if that solves your issue?

**Comment by Abel7x** [comment]
Nope it didn’t work. 

-- 
Abel Vivanco
Sent with Airmail

On January 22, 2016 at 04:08:02, Dorian Peake (notifications@github.com) wrote:

Can you try cleaning the Xcode project (CMD + OPTION + SHIFT + K) and see if that solves your issue?

**Comment by dozzman** [comment]
I've just performed a fresh clone and run of the example application -- everything seems to be working fine so it would be good to get some more info about what might be going on in your case. If you're able to stick your example app setup in a public repo, I can have a look. Please note that the example application requires you to set up the application with the verify-ios-sdk just like any other project.

https://docs.nexmo.com/sdks/verify-sdk/verify-sdk-for-iOS/verify-push-sample

Once you add the verify-ios-sdk.xcodeproj to the example app and drag the framework files into the Embedded Binaries section of the target, it should be fine.

**Comment by dozzman** [comment]
If you're having these issues with git clone, you can try and download the latest release from https://github.com/Nexmo/verify-ios-sdk/releases as a zip file, clean the project and add the SDK to your project from here. If this works then let me know and I'll investigate any issues with the latest trunk version.
