### ISSUE TITLE
iOS 10 Error Message

### ISSUE THREAD

**Issue by sschizas** [Nexmo/verify-ios-sdk#7]
I test my app against iOS 10 version and i got an error from Verify that this version of iOS is not supported.

Can you please let me know why I get this message?

**Comment by RajeshHuria** [comment]
/VerifyIosSdk/HttpResponse.swift:20:60: Expected member name or constructor call after type name

I am not able to build my app anymore :(

**Comment by dozzman** [comment]
@machelix could you please create a separate issue for what you are experiencing, along with your Xcode version; swift version by calling `swift -version` from the terminal; and the iOS version you are testing on.

**Comment by dozzman** [comment]
@n3trino I have a feeling I understand what is going on -- could you paste the following snippets in your `AppDelegate.applicationDidFinishLaunchingWithOptions` method and paste the output here.

``` Swift
print("systemName = \(UIDevice.currentDevice().systemName)")
print("systemVersion = \(UIDevice.currentDevice().systemVersion)")
```

**Comment by sschizas** [comment]
@dozzman here is the print out:

systemName = iOS
systemVersion = 10.0

**Comment by anton-ogarkov** [comment]
+1. I am experiencing the same problem.

**Comment by georgianacristina** [comment]
+1. I have the same problem

**Comment by derekmorin** [comment]
+1 Same problem

**Comment by andumorie** [comment]
+1 same problem :<

**Comment by dozzman** [comment]
We've made a few changes, can someone confirm whether or not you're still having the issue?

**Comment by georgianacristina** [comment]
Yes, it's working now. Thank you!

**Comment by andumorie** [comment]
Confirmed, working. Thanks!

**Comment by dozzman** [comment]
Alrighty thanks for your responses all. I'll assume that no further comments means this problem is officially resolved and the issue can be closed.
