### ISSUE TITLE
Swift 3.0 compatibility 

### ISSUE THREAD

**Issue by civocr** [Nexmo/verify-ios-sdk#8]
Hey there,

Is there any short term plans to support swift 3.0?

I have other frameworks using 3.0 and can't compile the app with this framework included

**Comment by fsdafdsafsda** [comment]
me to

**Comment by jodihum** [comment]
@civocr and @fsdafdsafsda 

We have put a beta swift 3 version of the SDK on the Swift3 branch.   Please note that only the SDK itself has been updated for swift 3, not the example apps.

Also, you might find that you need to enable Keychain Sharing on your app if you haven't already.  You do this by selecting your app in the project navigator, choosing your app target, opening the Capabilities tab, and switching Keychain Sharing to On. 

Cheers
Jodi

**Comment by sschizas** [comment]
@jodihum please include cocoapods with swift 3 upgrade of nexmo SDK

**Comment by civocr** [comment]
@n3trino sorry I didn't receive a notification about this ;/

I've got it working in one project, the other project has Module 'VerifyIosSdk' not found which is weird, because it compiled before

**Comment by shams-ahmed** [comment]
Version 1.0.4 is swift 3.0 compatible and supports pods:

```
pod 'NexmoVerify'
```
